(defun reduce_exp(lst)
	(cond ((atom (reduce_exp_help lst)) (reduce_exp_help lst))
		  ((equal 1 (length (reduce_exp_help lst))) (cond ((equal '* (car (reduce_exp_help lst))) 1)
		  												  (t (car (reduce_exp_help lst)))))
		  (t (reduce_exp_help lst))))

(defun reduce_exp_help (lst)
	(cond ((null lst) ())
		  ((atom lst) (list lst))
		  ((atom (car lst)) (cond ((equal '+ (car lst)) (cond ((equal 1 (length (judge_if_add_zero (cdr lst)))) (judge_if_add_zero (cdr lst)))
		  													  ((equal 0 (length (judge_if_add_zero (cdr lst)))) 0)  
		  													  (t (cons (car lst) (judge_if_add_zero (cdr lst))))))
								  ((equal '* (car lst)) (cond ((equal nil (judge_if_mul_zero (cdr lst))) 0)
								  							  (t (cond ((equal 1 (length (judge_if_mul_one (cdr lst)))) (judge_if_mul_one (cdr lst)))
								  							  	       (t (cons (car lst) (judge_if_mul_one (cdr lst))))))))
								  ((equal '/ (car lst)) (cond ((or (equal 0 (reduce_exp_help (cadr lst))) (equal '(0) (reduce_exp_help (cadr lst))) (equal nil (reduce_exp_help (cadr lst)))) 0)
								  								   (t (cond ((equal '(1) (reduce_exp_help (caddr lst))) (reduce_exp_help (cadr lst)))
								  								   			(t (cons (car lst) (reduce_exp_help (cdr lst))))))))
								  ((equal '% (car lst)) (cond ((or (equal 0 (reduce_exp_help (caddr lst))) (equal '(0) (reduce_exp_help (caddr lst))) (equal nil (reduce_exp_help (caddr lst)))) '(1))
								  								   (t (cond ((equal '(1) (reduce_exp_help (caddr lst))) (reduce_exp_help (cadr lst)))
								  								   			(t (cons (car lst) (reduce_exp_help (cdr lst))))))))
								  (t (cons (car lst) (reduce_exp_help (cdr lst))))))
		  (t (cons (reduce_exp_help (car lst)) (reduce_exp_help (cdr lst))))))

(defun judge_if_mul_zero (lst)
	(cond ((null lst) t)
		  ((atom (car lst)) (cond ((equal 0 (car lst)) ())
								  (t (judge_if_mul_zero (cdr lst)))))
		  (t (cond ((or (equal 0 (reduce_exp_help (car lst))) (equal nil (reduce_exp_help (car lst))) (equal nil (judge_if_mul_zero (cdr lst)))) ())
		  	       (t t)))))

(defun judge_if_add_zero (lst)
	(cond ((null lst) ())
		  ((atom (car lst)) (cond ((equal 0 (car lst)) (judge_if_add_zero (cdr lst)))
		  						  (t (cons (car lst) (judge_if_add_zero (cdr lst))))))
		  (t (cond ((equal 0 (reduce_exp_help (car lst))) (judge_if_add_zero (cdr lst)))
		  		   (t (cond ((equal 1 (length (reduce_exp_help (car lst))))  (append (reduce_exp_help (car lst)) (judge_if_add_zero (cdr lst))))
		  		   			(t (cons (reduce_exp_help (car lst)) (judge_if_add_zero (cdr lst))))))))))

(defun judge_if_mul_one(lst)
	(cond ((null lst) ())
		  ((atom (car lst)) (cond ((equal 1 (car lst)) (judge_if_mul_one (cdr lst)))
		  						  (t (cons (car lst) (judge_if_mul_one (cdr lst))))))
		  (t (cond ((equal '(1) (reduce_exp_help (car lst))) (judge_if_mul_one (cdr lst)))
		  	       (t (cond ((equal 1 (length (reduce_exp_help (car lst)))) (append (reduce_exp_help (car lst)) (judge_if_mul_one (cdr lst))))
		  	       	        (t (cons (reduce_exp_help (car lst)) (judge_if_mul_one (cdr lst))))))))))