(load "C:/Users/alari/Desktop/Task-planner-structures-16.lisp")
(load "C:/Users/alari/Desktop/Task-planner-testcases-16.lisp")
(load "C:/Users/alari/Desktop/Task-planner-initial-16.lisp")
(defun run()
	(testing)
)